name: Online Competition

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  online-competition:
    # Skip this job if running on the main repo to prevent failing CI/CD. Only run on student forks.
    if: ${{ github.repository != 'utiasDSL/lsy_drone_racing' }}

    runs-on: ubuntu-latest
    env:
      KAGGLE_USERNAME: ${{ secrets.KaggleUsername }}
      KAGGLE_KEY: ${{ secrets.KaggleKey }}

    steps:
      - uses: actions/checkout@v4

      # 安装系统依赖，解决 rtree 安装失败问题
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libspatialindex-dev

      - name: Setup Pixi (installs pixi + caches envs)
        uses: prefix-dev/setup-pixi@v0.9.0
        with:
          pixi-version: v0.49.0
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
          environments: online-submission
          activate-environment: false
          locked: true

      - name: Create online-submission times
        run: pixi run create-submission

      - name: Export with kaggle
        run: pixi run export-submission
